[project]
name = 'vault-flow'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.vault-flow]
path = 'contracts/vault-flow.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
